Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/debian-12"
    vm1.vm.network "private_network", ip: "192.168.56.11"
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-20.04"
    vm2.vm.network "private_network", ip: "192.168.56.12"
    vm2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y curl
    SHELL
  end
end
