Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "vm#{i}" do |vm|
      vm.vm.box = "bento/ubuntu-20.04"
      vm.vm.network "private_network", ip: "192.168.56.2#{i}"
      vm.vm.network "forwarded_port", guest:80, host: 8080 + i 
      vm.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
      SHELL
    end
  end
end
