Vagrant.configure("2") do |config|
  config.vm.define "debian1" do |debian1|
    debian1.vm.box = "debian/bullseye64"
    debian1.vm.network "private_network", ip: "192.168.56.101"
    debian1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip apache2 libapache2-mod-wsgi-py3
      pip3 install django
      systemctl start apache2
      systemctl enable apache2
    SHELL
  end

  config.vm.define "debian2" do |debian2|
    debian2.vm.box = "debian/bullseye64"
    debian2.vm.network "private_network", ip: "192.168.56.102"
    debian2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3 python3-pip apache2 libapache2-mod-wsgi-py3
      pip3 install django
      systemctl start apache2
      systemctl enable apache2
    SHELL
  end

  config.vm.define "debian3" do |debian3|
    debian3.vm.box = "debian/bullseye64"
    debian3.vm.network "private_network", ip: "192.168.56.103"
    debian3.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y mysql-server
      systemctl start mysql
      systemctl enable mysql
    SHELL
  end
end
