version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swarm-net

  python-service1:
    image: python:3.9
    command: python -m http.server 8000
    networks:
      - swarm-net

  python-service2:
    image: python:3.9
    command: python -m http.server 8000
    networks:
      - swarm-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - swarm-net

networks:
  swarm-net:

volumes:
  mysql_data:
