apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  containers:
  - image: nginx:latest
    name: web
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
