Vagrant.configure("2") do |config|
  config.vm.define "master" do |master|
    master.vm.box = "debian/bullseye64"
    # master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.101"
    master.vm.synced_folder ".", "/vagrant"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
    end
    master.vm.provision "shell", path: "install_docker_k8s.sh"
    # master.vm.provision "shell", inline: <<-SHELL
    #   # Initialize Kubernetes master
    #   sudo kubeadm init --apiserver-advertise-address=192.168.56.101 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=Mem,FileExisting-socat

    #   # Set up kubeconfig for vagrant user
    #   mkdir -p /home/vagrant/.kube
    #   sudo cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    #   sudo chown vagrant:vagrant /home/vagrant/.kube/config

    #   # Install Flannel network plugin
    #   kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

    #   # Generate join command
    #   kubeadm token create --print-join-command > /vagrant/kubeadm_join.sh
    # SHELL
  end

  (2..3).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = "debian/bullseye64"
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.10#{i}"
      worker.vm.provision "shell", path: "install_docker_k8s.sh"
      # worker.vm.provision "shell", inline: <<-SHELL
      #   # Join the Kubernetes cluster
      #   sudo sh /vagrant/kubeadm_join.sh
      # SHELL
    end
  end
end